### ISSUE TITLE
Problem with useTrimesh and Physics

### ISSUE THREAD

**Issue by ArchKa** [Sean-Bradley/React-Three-Fiber-Boilerplate#2]
Hello, 

I noticed that the physics of useTrimesh collides well with useSphere and usePlane but not with useBox, useCylinder etc...
I took the example from your trimeshContact branch and it seems that it is the same for your project

Do you have a solution ? thanks in advance

**Comment by Sean-Bradley** [comment]
This is how Cannon works.
This is not a problem with my boilerplate.
See the table at https://sbcode.net/threejs/physics-cannonjs/#supported-cannonjs-shape-collisions

Cannon is slow when you start doing complcated shapes, such as Trimesh or ConvexPolyhedron. 

When your shapes get more sophistictaed,  consider using a compound shape of spheres. It is much faster.
https://sbcode.net/threejs/compounds-versus-convex-polyhedrons/

Or consider using Rapier. 
I have no R3F Rapier examples yet, but I do vanilla.
https://sbcode.net/threejs/physics-rapier/
