### ISSUE TITLE
Fisheye code is missing?

### ISSUE THREAD

**Issue by fabiopolimeni** [Sean-Bradley/React-Three-Fiber-Boilerplate#3]
Hi Sean, I was wondering if the https://sbcode.net/react-three-fiber/fisheye/ code is missing or is somewhere I can't find. The code example is incomplete, as the Fisheye and Panorama components do not exist, and there is no code here on the repo. Is this still WIP? Thank you very much for this sort of resources, very much needed, considered the little amount of documentation on the fiber and drei examples ;)

**Comment by Sean-Bradley** [comment]
I didnt add it, the repo alrady has too many branches to manage.
The complete code is here https://sbedit.net/286a29be1a4cb0708b08ba8eccf975b3562a0393

**Comment by fabiopolimeni** [comment]
Oh, thank you, I missed that button on the pictures :)

**Comment by Sean-Bradley** [comment]
Here, I just added it to the repo for you. 
[fisheye](https://github.com/Sean-Bradley/React-Three-Fiber-Boilerplate/tree/fisheye) branch.

```
git clone https://github.com/Sean-Bradley/React-Three-Fiber-Boilerplate.git
cd React-Three-Fiber-Boilerplate
git checkout fisheye
npm install
npm start
```
